### ISSUE TITLE
Investigate the separation of strap from gumboot or at least Rails

### ISSUE THREAD

**Issue by rianniello** [ausaccessfed/aaf-gumboot#15]
[`strap.rb`](https://github.com/ausaccessfed/aaf-gumboot/blob/develop/lib/gumboot/strap.rb) requires Rails dependencies (`active_support`) to function. I discovered this in a Sinatra app.

This is the output while running `strap.rb`

```
The Gemfile's dependencies are satisfied
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/aaf-gumboot-9fdbc36b7f8b/lib/gumboot/strap.rb:2:in `require': cannot load such file -- active_support/core_ext/hash/deep_merge (LoadError)
    from /usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/aaf-gumboot-9fdbc36b7f8b/lib/gumboot/strap.rb:2:in `<top (required)>'
    from ./bin/setup:10:in `require'
    from ./bin/setup:10:in `<main>'
```

Makes me think separating `strap` to be independent of gumboot or at least rails so we're able to use this functionality for all frameworks.

Current workaround is to add this in Gemfile:

```
gem 'activesupport', require: false
```

**Comment by smangelsdorf** [comment]
The issue here is that `Strap` itself **is** the part of Gumboot which requires the `activesupport` gem, so we'd need to reimplement the `active_support/core_ext/hash/deep_merge` feature ourselves or source it from a different gem.
