### ISSUE TITLE
Refactor APIConstraints class to be part of Gumboot

### ISSUE THREAD

**Issue by smangelsdorf** [ausaccessfed/aaf-gumboot#18]
The only thing that changes per application is the part of the version string for the application name + API version. If that part of the string was provided by the application, the implementation could be provided by Gumboot:

```ruby
  namespace :api, defaults: { format: 'json' } do
    v1 = Gumboot::APIConstraints.new('example-app.v1', default: true)
    scope constraints: v1 do
      resources :xyz, param: :uid, only: [:show, :create, :update, :destroy]
    end
  end
```

**Comment by bradleybeddoes** [comment]
> provided by Gumboot

Do you mean an example implementation in documentation as we do for other app models at the moment?

**Comment by smangelsdorf** [comment]
No, I mean a class in the Gumboot project, like `Strap` is currently.

**Comment by bradleybeddoes** [comment]
My hesitation then would be that Gumboot doesn't currently provide app 'logic' per se and this would be a change to that nice delineation in my mind between specs/support and real app code.

Thoughts?

**Comment by smangelsdorf** [comment]
It is a fundamental change to Gumboot, that much is true. I recall there was a long discussion that ended with the current situation. Maybe it's still all valid.

On further thought, my hesitation here would be around introducing a split approach... providing **one** class directly from Gumboot, and the rest in the application itself. That's arguably worse than whatever code duplication we're solving.

If the `APIConstraints` aren't being moved to shared code, there's no point refactoring it to take the app name as a parameter (since it is actually an *extra* moving part over the current situation for no real benefit).

**Comment by bradleybeddoes** [comment]
+1 to continuing status quo until a better argument for change comes along.
