### ISSUE TITLE
.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:323:in 'safe_load': wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by ArthurZheng** [ausaccessfed/aaf-gumboot#72]
Gumboot does not support Ruby 3.

When running `./bin/setup` in Rapid IdP manager, the script breaks with below error message: 

```
.rbenv/versions/3.1.1/lib/ruby/3.1.0/psych.rb:323:in 'safe_load': wrong number of arguments (given 2, expected 1) (ArgumentError)

	from ~/rapid-idp-manager/vendor/bundlegs/ruby/3.1.0/gems/aaf-gumboot-2.5.1/lib/gumboot/strap.rb:126:in `safe_load'
	from ~/rapid-idp-manager/vendor/bundlegs/ruby/3.1.0/gems/aaf-gumboot-2.5.1/lib/gumboot/strap.rb:131:in `merge_config'
	from ~/rapid-idp-manager/vendor/bundlegs/ruby/3.1.0/gems/aaf-gumboot-2.5.1/lib/gumboot/strap.rb:101:in `block in update_local_configuration'
	from ~/rapid-idp-manager/vendor/bundlegs/ruby/3.1.0/gems/aaf-gumboot-2.5.1/lib/gumboot/strap.rb:96:in `each'
	from ~/rapid-idp-manager/vendor/bundlegs/ruby/3.1.0/gems/aaf-gumboot-2.5.1/lib/gumboot/strap.rb:96:in `update_local_configuration'
	from ./bin/setup:18:in `<main>'
  
```

**Comment by ArthurZheng** [comment]
Hey @waldofouche, this is the error you had the other day when you were trying to set up RIdP Manager on your machine. I didn't have this issue unless I blew away my local dev DB and ran `./bin/setup` agagin.

**Comment by waldofouche** [comment]
Ah! Good catch, is it worth updating Gumboot or is it easier to just remove it from Rapid IdP?

**Comment by ArthurZheng** [comment]
I have a fix in gumboot. PR coming soon.

**Comment by vladimir-mencl-eresearch** [comment]
Hi guys, you may want to close this issue now - it did not auto-close because the reference back to this issue in #74 did not match the syntax...

**Comment by ArthurZheng** [comment]
Thanks @vladimir-mencl-eresearch. Closing issue now
