### ISSUE TITLE
release latest fixes please

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/aaf-gumboot#80]
Hi @phyzical ,

Could you please make a release with fixes from latest PRs?  I accidentally made #79 against `master`, not develop, so this may need either merging `master` into `develop` or `develop` into `master` first (depending on where the release is built).

Thanks a lot in advance - will be really handy for me to get #79 included in the release, I'm otherwise getting rspec errors when running against MySQL.

Cheers,
Vlad

**Comment by phyzical** [comment]
@vladimir-mencl-eresearch published as 2.6.3

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the quick action!

**Comment by vladimir-mencl-eresearch** [comment]
PS: Not sure whether worth doing an explicit down-merge from `master` to `develop` - to avoid this tripping anyone later...

**Comment by phyzical** [comment]
ive slowly been ditching the development paradigm, outdated approach imo, didnt notice that master was missing anything from development so master is now in charge

**Comment by vladimir-mencl-eresearch** [comment]
Ah, OK, thanks, makes sense.  All happy for `master` to be the master in charge.

**Comment by vladimir-mencl-eresearch** [comment]
I can confirm `master` has all the commits from `develop` - and with `master` in charge, we don't need to worry anymore about getting commits from `master` to `develop`.

Agree it's easier with just one branch commits get merged into.  (In particular if nobody commits to `master` directly and all commits go via a PR).
